# Generated by Django 4.2.6 on 2023-10-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество товаров для покупки')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
